import type { NextPage } from 'next'
import Head from 'next/head'
import DataGridDemo from '../components/MaterialUIData';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Add Button in Row <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <DataGridDemo />
      </main>
    </div>
  )
}

export default Home
